In [29]:
import pandas as pd
import numpy as np
import matplotlib as mlt
import statistics as stat
import seaborn as sns

In [30]:
data = pd.read_csv('Dataset3.csv',index_col=0)


In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49994 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   cust_number             49994 non-null  object 
 1   name_customer           49994 non-null  object 
 2   clear_date              39994 non-null  object 
 3   doc_id                  49994 non-null  int64  
 4   posting_date            49994 non-null  object 
 5   document_create_date    49994 non-null  object 
 6   document_create_date.1  49994 non-null  object 
 7   due_in_date             49994 non-null  object 
 8   total_open_amount       49994 non-null  float64
 9   baseline_create_date    49994 non-null  object 
 10  cust_payment_terms      49994 non-null  object 
 11  invoice_id              49994 non-null  float64
 12  isOpen                  49994 non-null  int64  
 13  Delay                   39994 non-null  float64
 14  Time_given              49994 non-null

In [32]:
data.head()


cust_number       name_customer  clear_date      doc_id posting_date  \
0   200769623        WAL-MAR corp  2020-11-02  1930438491   2020-01-26   
1   200980828              BEN E   2019-08-08  1929646410   2019-07-22   
2   200792734          MDV/ trust  2019-12-30  1929873765   2019-09-14   
3   140105686            SYSC llc         NaN  2960623488   2020-03-30   
4   200769623  WAL-MAR foundation  2019-11-25  1930147974   2019-11-13   

  document_create_date document_create_date.1 due_in_date  total_open_amount  \
0           2020-01-25             2020-01-26  2020-02-10        4054214.016   
1           2019-07-22             2019-07-22  2019-08-11        5950348.020   
2           2019-09-14             2019-09-14  2019-09-29         168363.342   
3           2020-03-30             2020-03-30  2020-04-10         194055.357   
4           2019-11-13             2019-11-13  2019-11-28        2475056.763   

  baseline_create_date cust_payment_terms    invoice_id  isOpen  Delay  \
0           2020-01-26               NAH4  1.930438e+09       0  266.0   
1           2019-07-22               NAD1  1.929646e+09       0   -3.0   
2           2019-09-14               NAA8  1.929874e+09       0   92.0   
3           2020-03-31               CA10  2.960623e+09       1    NaN   
4           2019-11-13               NAH4  1.930148e+09       0   -3.0   

   Time_given  Time_taken  Time_variance  
0          16       282.0          266.0  
1          20        17.0           -3.0  
2          15       107.0           92.0  
3          11         NaN            NaN  
4          15        12.0           -3.0

In [33]:
data['clear_date'] = pd.to_datetime(data['clear_date'])
data['posting_date'] = pd.to_datetime(data['posting_date'])
data['document_create_date'] = pd.to_datetime(data['document_create_date'])
data['document_create_date.1'] = pd.to_datetime(data['document_create_date.1'])
data['due_in_date'] = pd.to_datetime(data['due_in_date'])
data['baseline_create_date'] = pd.to_datetime(data['baseline_create_date'])
data['Time_given'] = (data['due_in_date'] - data['document_create_date']).dt.days
data['Time_taken'] = (data['clear_date'] - data['document_create_date']).dt.days
data['Time_variance'] = (data['Time_taken']-data['Time_given'])

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49994 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   cust_number             49994 non-null  object        
 1   name_customer           49994 non-null  object        
 2   clear_date              39994 non-null  datetime64[ns]
 3   doc_id                  49994 non-null  int64         
 4   posting_date            49994 non-null  datetime64[ns]
 5   document_create_date    49994 non-null  datetime64[ns]
 6   document_create_date.1  49994 non-null  datetime64[ns]
 7   due_in_date             49994 non-null  datetime64[ns]
 8   total_open_amount       49994 non-null  float64       
 9   baseline_create_date    49994 non-null  datetime64[ns]
 10  cust_payment_terms      49994 non-null  object        
 11  invoice_id              49994 non-null  float64       
 12  isOpen                  49994 non-null  int64 

In [35]:
target = 'isOpen'

In [36]:
def mycorr(x,y=data[target]):
    mat = np.corrcoef(x,y)
    print(mat)


In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49994 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   cust_number             49994 non-null  object        
 1   name_customer           49994 non-null  object        
 2   clear_date              39994 non-null  datetime64[ns]
 3   doc_id                  49994 non-null  int64         
 4   posting_date            49994 non-null  datetime64[ns]
 5   document_create_date    49994 non-null  datetime64[ns]
 6   document_create_date.1  49994 non-null  datetime64[ns]
 7   due_in_date             49994 non-null  datetime64[ns]
 8   total_open_amount       49994 non-null  float64       
 9   baseline_create_date    49994 non-null  datetime64[ns]
 10  cust_payment_terms      49994 non-null  object        
 11  invoice_id              49994 non-null  float64       
 12  isOpen                  49994 non-null  int64 

In [38]:
mycorr(data['Time_given'])

[[ 1.         -0.02333427]
 [-0.02333427  1.        ]]


In [39]:
mycorr(data['Time_taken'].notnull(),data['isOpen'])

[[ 1. -1.]
 [-1.  1.]]


In [40]:
mycorr(data['Time_variance'].notnull(),data['Time_taken'].notnull())

[[1. 1.]
 [1. 1.]]


In [41]:
data.shape


(49994, 17)

In [42]:
for i in data:
    if data[i].isnull().sum()>0:
        print(i,data[i].isnull().sum())

clear_date 10000
Delay 10000
Time_taken 10000
Time_variance 10000


In [43]:
data.head()

cust_number       name_customer clear_date      doc_id posting_date  \
0   200769623        WAL-MAR corp 2020-11-02  1930438491   2020-01-26   
1   200980828              BEN E  2019-08-08  1929646410   2019-07-22   
2   200792734          MDV/ trust 2019-12-30  1929873765   2019-09-14   
3   140105686            SYSC llc        NaT  2960623488   2020-03-30   
4   200769623  WAL-MAR foundation 2019-11-25  1930147974   2019-11-13   

  document_create_date document_create_date.1 due_in_date  total_open_amount  \
0           2020-01-25             2020-01-26  2020-02-10        4054214.016   
1           2019-07-22             2019-07-22  2019-08-11        5950348.020   
2           2019-09-14             2019-09-14  2019-09-29         168363.342   
3           2020-03-30             2020-03-30  2020-04-10         194055.357   
4           2019-11-13             2019-11-13  2019-11-28        2475056.763   

  baseline_create_date cust_payment_terms    invoice_id  isOpen  Delay  \
0           2020-01-26               NAH4  1.930438e+09       0  266.0   
1           2019-07-22               NAD1  1.929646e+09       0   -3.0   
2           2019-09-14               NAA8  1.929874e+09       0   92.0   
3           2020-03-31               CA10  2.960623e+09       1    NaN   
4           2019-11-13               NAH4  1.930148e+09       0   -3.0   

   Time_given  Time_taken  Time_variance  
0          16       282.0          266.0  
1          20        17.0           -3.0  
2          15       107.0           92.0  
3          11         NaN            NaN  
4          15        12.0           -3.0

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49994 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype         
---  ------                  --------------  -----         
 0   cust_number             49994 non-null  object        
 1   name_customer           49994 non-null  object        
 2   clear_date              39994 non-null  datetime64[ns]
 3   doc_id                  49994 non-null  int64         
 4   posting_date            49994 non-null  datetime64[ns]
 5   document_create_date    49994 non-null  datetime64[ns]
 6   document_create_date.1  49994 non-null  datetime64[ns]
 7   due_in_date             49994 non-null  datetime64[ns]
 8   total_open_amount       49994 non-null  float64       
 9   baseline_create_date    49994 non-null  datetime64[ns]
 10  cust_payment_terms      49994 non-null  object        
 11  invoice_id              49994 non-null  float64       
 12  isOpen                  49994 non-null  int64 

In [45]:
data.describe()

doc_id  total_open_amount    invoice_id        isOpen  \
count  4.999400e+04       4.999400e+04  4.999400e+04  49994.000000   
mean   2.011340e+09       2.345756e+06  2.011340e+09      0.200024   
std    2.766335e+08       2.764921e+06  2.766335e+08      0.400022   
min    1.928502e+09       5.378400e+01  1.928502e+09      0.000000   
25%    1.929342e+09       3.601862e+05  1.929342e+09      0.000000   
50%    1.929964e+09       1.297599e+06  1.929964e+09      0.000000   
75%    1.930619e+09       3.467049e+06  1.930619e+09      0.000000   
max    2.960636e+09       4.994392e+07  2.960636e+09      1.000000   

              Delay    Time_given    Time_taken  Time_variance  
count  39994.000000  49994.000000  39994.000000   39994.000000  
mean       1.864405     17.930532     19.917088       1.864405  
std       90.991393     10.469005     91.092127      90.991393  
min     -326.000000    -34.000000   -291.000000    -326.000000  
25%       -5.000000     15.000000     11.000000      -5.000000  
50%        0.000000     16.000000     16.000000       0.000000  
75%        6.000000     17.000000     33.000000       6.000000  
max      316.000000    122.000000    338.000000     316.000000

In [46]:
data.nunique()

cust_number                1098
name_customer              4193
clear_date                  403
doc_id                    48833
posting_date                506
document_create_date        507
document_create_date.1      506
due_in_date                 547
total_open_amount         44379
baseline_create_date        506
cust_payment_terms           74
invoice_id                48833
isOpen                        2
Delay                       595
Time_given                  116
Time_taken                  607
Time_variance               595
dtype: int64

In [47]:
data.corr()

doc_id  total_open_amount  invoice_id    isOpen  \
doc_id             1.000000           0.101620    1.000000 -0.007517   
total_open_amount  0.101620           1.000000    0.101620  0.014595   
invoice_id         1.000000           0.101620    1.000000 -0.007517   
isOpen            -0.007517           0.014595   -0.007517  1.000000   
Delay              0.015720          -0.001594    0.015720       NaN   
Time_given        -0.112309          -0.065970   -0.112309 -0.023334   
Time_taken         0.002575          -0.009050    0.002575       NaN   
Time_variance      0.015720          -0.001594    0.015720       NaN   

                      Delay  Time_given  Time_taken  Time_variance  
doc_id             0.015720   -0.112309    0.002575       0.015720  
total_open_amount -0.001594   -0.065970   -0.009050      -0.001594  
invoice_id         0.015720   -0.112309    0.002575       0.015720  
isOpen                  NaN   -0.023334         NaN            NaN  
Delay              1.000000   -0.049302    0.993109       1.000000  
Time_given        -0.049302    1.000000    0.068086      -0.049302  
Time_taken         0.993109    0.068086    1.000000       0.993109  
Time_variance      1.000000   -0.049302    0.993109       1.000000

In [48]:
data.cov()


doc_id  total_open_amount    invoice_id  \
doc_id             7.652609e+16       7.772568e+13  7.652609e+16   
total_open_amount  7.772568e+13       7.644785e+12  7.772568e+13   
invoice_id         7.652609e+16       7.772568e+13  7.652609e+16   
isOpen            -8.317763e+05       1.614301e+04 -8.317763e+05   
Delay              3.983671e+08      -4.037067e+05  3.983671e+08   
Time_given        -3.252555e+08      -1.909571e+06 -3.252555e+08   
Time_taken         6.533230e+07      -2.293776e+06  6.533230e+07   
Time_variance      3.983671e+08      -4.037067e+05  3.983671e+08   

                          isOpen         Delay    Time_given    Time_taken  \
doc_id            -831776.319646  3.983671e+08 -3.252555e+08  6.533230e+07   
total_open_amount   16143.007518 -4.037067e+05 -1.909571e+06 -2.293776e+06   
invoice_id        -831776.319646  3.983671e+08 -3.252555e+08  6.533230e+07   
isOpen                  0.160018  0.000000e+00 -9.772001e-02  0.000000e+00   
Delay                   0.000000  8.279434e+03 -4.794710e+01  8.231486e+03   
Time_given             -0.097720 -4.794710e+01  1.096001e+02  6.628909e+01   
Time_taken              0.000000  8.231486e+03  6.628909e+01  8.297776e+03   
Time_variance           0.000000  8.279434e+03 -4.794710e+01  8.231486e+03   

                   Time_variance  
doc_id              3.983671e+08  
total_open_amount  -4.037067e+05  
invoice_id          3.983671e+08  
isOpen              0.000000e+00  
Delay               8.279434e+03  
Time_given         -4.794710e+01  
Time_taken          8.231486e+03  
Time_variance       8.279434e+03

In [49]:
data.nunique()

cust_number                1098
name_customer              4193
clear_date                  403
doc_id                    48833
posting_date                506
document_create_date        507
document_create_date.1      506
due_in_date                 547
total_open_amount         44379
baseline_create_date        506
cust_payment_terms           74
invoice_id                48833
isOpen                        2
Delay                       595
Time_given                  116
Time_taken                  607
Time_variance               595
dtype: int64

In [50]:
orig = pd.read_csv('Dataset.csv',index_col=0)

In [51]:
print(orig.nunique())

cust_number                1099
name_customer              4197
clear_date                  403
buisness_year                 2
doc_id                    48839
posting_date                506
document_create_date        507
document_create_date.1      506
due_in_date                 547
invoice_currency              2
document type                 2
posting_id                    1
area_business                 0
Unnamed: 14                  17
total_open_amount         44349
baseline_create_date        506
cust_payment_terms           74
invoice_id                48833
isOpen                        2
dtype: int64
